services:
  - type: web
    name: zerodha-clone-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        value: <<your_mongoDB_url_here>>
